[package]
name = "vim_snake"
version = "0.1.0"
authors = ["patmood <patrick.n.moody@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.7"
